gravitl/netclient

.github/workflows/test.yml
Signed-off-by: Matthew R. Kasun <mkasun@nusak.ca>
=> update actions to v3

cmd/install.go, config/config.go, functions/install.go
check if binary is attempting to be installed on top of itself.  If so, print warning and abort.
=> cleanup install command

cmd/connect.go, cmd/install.go, cmd/join.go, cmd/root.go, cmd/version.go, config/config.go, config/node.go, functions/connect.go, functions/daemon.go, functions/install.go, functions/join.go, functions/list.go, functions/localport.go, functions/mqhandlers.go, functions/mqpublish.go, functions/pull.go, local/local.go, main.go, ncutils/netclientutils.go
minor fixes
remove debug logs
fixed usage/help
=> Final cleanup 

cmd/join.go, functions/join.go
This PR adds an error return to join so errors can be handled on the GUI
=> tech(GRA-726): refactor Join to return error

functions/join.go, functions/mqpublish.go, functions/pull.go, go.mod, go.sum
=> Httpclient update

cmd/root.go
Export InitConfig so it can be consumed by GUI
=> tech(GRA-726): export InitConfig function

functions/uninstall.go
check before leaving a network otherwise it panics when user tries to leave a network they are not part of
=> fix(GRA-609av): check if joined before leaving network

daemon/common_linux.go
Fixes https://github.com/gravitl/netmaker/issues/1760
=> Fix egress gateway disconnect on reboot

gui/frontend/src/pages/NetworkDetailsPage.tsx
=> style(GRA-772): rearrange page based on feedback

config/node.go, config/oldconfig.go, functions/join.go, functions/mqhandlers.go, nmproxy/manager/manager.go, wireguard/types.go, wireguard/wireguard_darwin.go, wireguard/wireguard_linux.go, wireguard/wireguard_unix.go
-> set peers from join response
-> create interface only once
-> PersistentKeepalive type conversion fix
=> netclient fixes

config/config.go, functions/daemon.go, functions/mqhandlers.go, nmproxy/config/config.go, nmproxy/config/peer_config.go, nmproxy/manager/manager.go, nmproxy/models/models.go, nmproxy/nm-proxy.go, nmproxy/peer/peer.go, nmproxy/proxy/proxy_helper.go, nmproxy/server/server.go, nmproxy/wg/wg.go
-> runs a metrics thread to collect metrics for the peers when proxy is disabled on host
=> Proxy Noproxy peers 

functions/daemon.go, functions/mqhandlers.go, go.mod, go.sum, nmproxy/config/config.go, nmproxy/config/peer_config.go, nmproxy/manager/manager.go, nmproxy/metrics/metrics.go, nmproxy/models/models.go, nmproxy/nm-proxy.go, nmproxy/peer/peer.go, nmproxy/proxy/proxy.go, nmproxy/proxy/proxy_helper.go, nmproxy/server/server.go
-> removed unused fields
-> mutex locks added as necessary to config
=> Proxy refactor cleanup

functions/daemon.go, nmproxy/config/config.go, nmproxy/manager/manager.go, nmproxy/nm-proxy.go, nmproxy/peer/peer.go, nmproxy/server/server.go
**This PR should be reviewed after PR #127 is merged**
Testing Steps:- @theguy951357 
1. kill the daemon and check if the daemon shuts down in a reasonable amount of time, it shouldn't take more than a few seconds.
-> you can test by soft killing the daemon `kill -15 <PID>`
=> Gra 987/bug daemon shutdown

functions/connect.go, functions/daemon.go, functions/uninstall.go
To test:
- Install Netclient
- Join a network with said Netclient
- **Bonus, join with 2 netclients
- Ensure a Node is present for a host
- Call `netclient uninstall`
- Ensure the Host and Nodes are removed from the DB via UI or CLI
- **Ensure Peers are correct if other Peer netclients were connected
=> included global publish for uninstall

.github/workflows/test.yml, functions/join.go
fix test
-- darwin-gui still fails to build ... workflow needs updating
=> Gra 1015 integration tests

.github/workflows/test.yml, functions/localport_unix.go
The freebsd build will pass once this PR is merged to develop
=> Gra 1015 darwin build

gui/app.go, gui/constants.go, gui/exported.go, gui/frontend/src/components/AppEventListener.tsx, gui/frontend/src/constants.ts, gui/frontend/src/pages/SettingsPage.tsx, gui/frontend/src/routes.tsx, gui/frontend/wailsjs/go/main/App.d.ts, gui/frontend/wailsjs/go/main/App.js, gui/frontend/wailsjs/go/models.ts, gui/types.go
TESTING STEPS:
1. Open NCGUI
2. Go to Settings from the File menu
3. Check that the host settings are correct
=> feat(GRA-1081): add hosts settings page

cmd/root.go, config/config.go, functions/daemon.go, gui/exported.go
TESTING STEPS: check that CI builds pass
=> fix(GRA-1103): use separate method to refresh configs for gui

nmproxy/router/firewall.go, nmproxy/router/firewall_linux.go, nmproxy/router/firewall_nonlinux.go
=> GRA-1054: return err if non of the firewalls are supported

go.mod, go.sum
=> update go mod in develop

functions/list.go
=> GRA-1143: fix list command output

go.mod, go.sum, nmproxy/manager/manager.go, nmproxy/packet/packet_helper.go, nmproxy/peer/peer.go, nmproxy/proxy/proxy_helper.go, nmproxy/server/server.go
should be tested against: https://github.com/gravitl/netmaker/pull/2007
=> GRA-1145: set peer port to relay host port for a relayed peer

functions/join.go
=> Gra 1150 and gra 1129 initial join

nmproxy/router/iptables_linux.go
=> GRA-1054: add egress nat rule for dest masquerade

nmproxy/nm-proxy.go
No testing is required just a fail-safe check
=> GRA-1269: exit if stun is not configured correctly on server

nmproxy/router/firewall_linux.go
=> GRA-1238: move nftable check below iptables

nmproxy/server/server.go
=> GRA-1317: add proxy transport message size to buffer size parameter

functions/mqhandlers.go
Just fixes a log, doesn't actually need to be paired with corresponding branch
No testing required
=> GRA-1324 fix log

functions/daemon.go, functions/mqhandlers.go
Handles registration events more synchronously
To test:
=> GRA-1326: adjusted host update handler for registration

gui/exported.go, gui/frontend/src/pages/LoginOption.tsx, gui/frontend/src/pages/TokenLogin.tsx, gui/frontend/tests/pages/LoginOptions.test.tsx, gui/frontend/tests/pages/TokenLogin.test.tsx, gui/frontend/wailsjs/go/main/App.d.ts, gui/frontend/wailsjs/go/main/App.js
TESTING STEPS:
1. Use netclient gui and click add network
2. Join a network by enrollment key
3. Check that the host is registered and joined the network(s) if applicable
=> feat(GRA-1300): add register by enrollment keys

config/config.go, config/config_windows.go, daemon/common_windows.go, functions/install.go
Updated winsw
Updated restart logic
Moved verbosity setting to whenever netclient is read
**To test**
=> Gra 1356 windows daemon edit

config/config_windows.go, wireguard/wireguard_windows.go
- adjust logging
- added check for existing adapter (prevents internet connectivity loss)
- ensured route setting
- Does **NOT** solve the port issue
To Test:
=> GRA-1363: windows hotfixes

functions/join.go, functions/register.go, go.mod, go.sum
- test with same branch on server
=> GRA-1363: set ports on register/join

config/config.go
-> copy global variable before updating to avoid panics
=> GRA-1389: copy variable before updating

nmproxy/manager/manager.go
https://github.com/gravitl/netmaker/pull/2120
=> GRA-1392: relay bug fix, Use peer remove flag to delete peer connection from proxy

functions/register.go
- update register to fetch interfaces before registration
title.
=> GRA-1394: added join function for interfaces

README.md, gui/frontend/package.json, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json, wails.json
updating to v0.18.4 for release
=> update to v0.18.4

README.md, gui/frontend/package-lock.json, gui/frontend/package.json, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json, wails.json
=> update develop to 0.18.5

functions/migrate.go
- Added check for ports and overwriting of netclient so it actually gets written
title.
N/A
=> GRA-1395: added listen port checks on migrate

cmd/pull.go, functions/mqhandlers.go, functions/pull.go, go.mod, go.sum, gui/exported.go, wireguard/wireguard_conf.go
- removed arguments from pull
- pull gets from every server
title.
https://github.com/gravitl/netmaker/pull/2142
=> GRA-1339: host pull

functions/localport.go, functions/mqhandlers.go
- Skip allowed IP contained addresses
- Skip reporting docker ifaces
title.
N/A
=> GRA-1437: avoid allowed IP endpoints, docker

nmproxy/proxy/proxy.go, nmproxy/server/server.go
1. Proxy to listen on all interfaces
2. comment out port tracking through metrics
=> GRA-1451: Listen Proxy on all interfaces

functions/mqhandlers.go, networking/server-pong.go
=> GRA-1458: run endpoint detection async

scripts/netclient.sh
=> update docker entrypoint for register/join changes

networking/client-ping.go, networking/server-pong.go, networking/types.go
=> GRA-1458: decrease ping-pong timeout, check if endpoint has actually changed before updating

functions/mqhandlers.go, go.sum, ncutils/netclientutils_darwin.go, ncutils/netclientutils_freebsd.go, ncutils/netclientutils_linux.go, ncutils/netclientutils_windows.go, networking/client-ping.go
endpoint nil check on endpoint detection
skip if bridge network for endpoint detection
=> GRA-1487: peer endpoint nil check,skip bridge networks for endpoint detection

wireguard/wireguard_linux.go
adding routes for egress ranges on peer fixed
=> GRA-1461: get netlink by name

wireguard/wireguard_linux.go
=> get netlink by name

nmproxy/router/firewall_linux.go, wireguard/wireguard_linux.go
=> Release v0.18.5

config/config.go
update logging verbosity on change
n/a
=> update logging verbosity when changed

README.md, gui/frontend/package.json, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json, wails.json
updating develop to v0.18.6
GRA-1407
N/A
N/A
=> update develop to v0.18.6

functions/localport.go, functions/mqhandlers.go, ncutils/netclientutils_darwin.go, ncutils/netclientutils_freebsd.go, ncutils/netclientutils_linux.go, ncutils/netclientutils_windows.go
=> Revert "added pointtopoint flag check & bridge check on iface reporting"

functions/localport.go, functions/mqhandlers.go, ncutils/netclientutils_darwin.go, ncutils/netclientutils_freebsd.go, ncutils/netclientutils_linux.go, ncutils/netclientutils_windows.go
=> added pointtopoint flag check & bridge check on iface reporting

.github/workflows/hotfix-release.yml
=> hotfix release workflow

functions/daemon.go, functions/mqhandlers.go, networking/server_addrs.go, routes/routes_windows.go, routes/util_windows.go, wireguard/wireguard_windows.go
- adds windows implementation
title.
- https://github.com/gravitl/netmaker/pull/2182
- repeat linux testing with windows machine
=> GRA-1205: windows implementation

.github/workflows/branchtest.yml
=> corrects branchname in workflow

.github/workflows/release.yml
have package job inherit secrets
temp remove windows/mac assets till signing is figured out
=> release workflow updates

nmproxy/packet/packet.go, nmproxy/proxy/proxy_helper.go, nmproxy/server/server.go
reduce the number of log messages if debug flag is not set
=> add debug check for some logs

.github/workflows/deletedroplets.yml
use id vice run_id to determine digital ocean droplet tag
verify DeleteDroplet workflow runs successfully
=> DO TAG determination for deleting droplets

README.md, gui/frontend/package.json, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json, wails.json
=> update develop to v0.18.7

functions/mqhandlers.go
=> correct case for UpdateKeys action

.github/workflows/deletedroplets.yml
send a discord message after branch test run with:
results
serverinfo
errors (if applicable)
n/a
n/a
workflow results
=> discord message after branch test run

release.md
=> notes for v0.18.7

.github/workflows/deletedroplets.yml
delete droplets even when previous workflow steps fail
2240
=> always delete droplets

nmproxy/router/nftables_linux.go
add forwarding rule for clients with nftables only
n/a
see NET-13
=> nftables forward rule

gui/frontend/tests/pages/LoginOptions.test.tsx, gui/frontend/tests/pages/NetworkDetails.test.tsx, gui/frontend/tests/pages/Networks.test.tsx, gui/frontend/tests/pages/TokenLogin.test.tsx, gui/frontend/tests/pages/UsernameLogin.test.tsx, gui/frontend/tests/tests.ts, gui/frontend/tests/utils.test.tsx
=> fix(NET-21): fix gui unit tests

config/config.go, functions/mqpublish.go, release.md
- correct detect firewall in use vice defaulting to iptables 
- detect if new firewall package installed (ie. iptables-nft) during checkin
see NET-17
=> firewall in use

gui/frontend/src/pages/SettingsPage.tsx
=> fix(NET-6): add iface name in GUI host settings

gui/exported.go, gui/frontend/src/App.tsx, gui/frontend/wailsjs/go/main/App.d.ts, gui/frontend/wailsjs/go/main/App.js, gui/main.go
=> fix(NET-6): add notification for unreachable daemon

config/config.go, config/gui.go, config/node.go, config/server.go, daemon/common_freebsd.go, functions/httpserver.go, gui/exported.go, gui/main.go, ncutils/netclientutils.go, release.md
netclient daemon gets available port for http server
port is saved to config file
netclient-gui uses config file to set http endpoint
see NET-29
=> check for available http port

.github/workflows/deletedroplets.yml
update the color of discord error messages
=> color of discord error messages

.github/workflows/deletedroplets.yml
include DO droplet tag in discord message
=> include DO droplet tag in discord message

functions/pull.go
https://github.com/gravitl/netmaker/pull/2246
=> NET-35: write to server config after pulling data

routes/routes_linux.go, routes/routes_unix.go, routes/routes_windows.go
skip creation of explicit server & peer routes if internet gateway not present
n/a
see GRA-1554
=> create explicit routes when internet gateway exist

config/config.go, functions/register.go, ncutils/netclientutils.go
replace ncutils.MakeRandomString with netmaker/logic.RandomString()
PR#2254 updates RadomString() in netmaker repo
=> use RandomString() from netmaker

functions/daemon.go, functions/mqhandlers.go
commented out endpoint detection
=> NET-85: comment out endpoint detection

functions/mqhandlers.go, go.mod, go.sum
gravitl/txeh was updated to match upstream txn2/txeh
=> txeh updates

config/config.go, functions/daemon.go, functions/mqpublish.go, go.mod, go.sum, nmproxy/nm-proxy.go, nmproxy/stun/stun.go
-> hole punch wiregaurd port
-> start proxy on dynamic free port available
https://github.com/gravitl/netmaker/pull/2344
=> NET-186: hole punch wg port, start proxy on free port available

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> version and release note updates

nmproxy/config/config.go, nmproxy/manager/manager.go, nmproxy/server/server.go
Removed Relay related code from proxy
No testing required
=> NET-282: remove relay implementation from proxy

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update version to 20.0.2 for develop

config/config.go, daemon/common_linux.go, functions/mqhandlers.go, functions/version_test.go
=> set autoupdate on host update

.github/workflows/branchtest.yml
output name for  netmaker branch name
=> output name

functions/mqhandlers.go
functional change at ~line 211
=> remove unrequired daemon restart & convert logs

nmproxy/stun/stun.go
=> NET-319: use global error, additional ip, port check

gui/app.go
=> fix(NET-231): fix copy/paste on mac

nmproxy/turn/turn_helper.go
=> NET-337: fix turn disconnect

nmproxy/router/iptables_linux.go, nmproxy/router/nftables_linux.go, wireguard/wireguard.go
-> Remove Drop rules
-> Set Foward Policy to Accept by default
https://github.com/gravitl/netmaker/pull/2401
a. Relay a Node
b. Relay two Nodes with same Relay Node
c. while Nodes are being relayed, make a node as a ingress gateway, check whether ext clients are able to reach relayed Nodes
d. Test egress behind a relay
=> Net 137 relays

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
updating develop to v0.20.3
no ticket number
no testing needed
=> update develop to v0.20.3

.github/workflows/branchtest.yml, cmd/root.go
check for wireguard presence on startup
=> wireguard check on startup

functions/httpserver.go, gui/frontend/package-lock.json, gui/main.go
=> fix(NET-244): use static http server port on windows

functions/daemon.go
=> Fix errors in error messages

cmd/root.go
=> Revert "wireguard check on startup"

functions/mqpublish.go
=> NET-390: restart daemon when listen port changes

config/config.go, functions/daemon.go, functions/mqpublish.go, go.mod, go.sum
=> adding free port check

config/config.go, ncutils/netclientutils_windows.go, nmproxy/common/common.go
=> Revert "windows binary path"

release.md
=> release notes for v0.20.3

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.20.4

functions/daemon.go, wireguard/wireguard.go, wireguard/wireguard_freebsd.go
- brings up netmaker interface in nc.Configure
- ignores error from wg.ConfigureDevice when peers are empty
=> Freebsd updates

release.md
=> v0.20.4 release notes

.github/workflows/deletedroplets.yml
save server name to be used by follow-on steps
=> save server name to environment

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.20.5

cmd/join.go, cmd/register.go, functions/httpserver.go, functions/register.go, functions/register_sso.go, gui/exported.go, gui/frontend/src/pages/TokenLogin.tsx
https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/416
=> fix(NET-416): bug with nc-gui register on windows

release.md
=> V0.20.5 release notes

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.20.6

functions/uninstall.go
add a log to uninstall stating to use add/remove program is using windows
[ ] install on windows
[ ] in a cmd prompt, call netclient uninstall
[ ] verify log is shown on windows and uninstall breaks
[ ] uninstall through the add/remove program
[ ] verify a clean uninstall from the windows machine
=> Net 439 windows uninstall

gui/constants.go
=> fix: correct docs link to .io tld

release.md
=> v0.20.6 release notes

functions/mqhandlers.go, functions/pull.go
=> fix sync, update host settings on pull

functions/mqhandlers.go, functions/pull.go
=> Release v0.20.6 Patch

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to 0.21.0

functions/mqhandlers.go, functions/mqpublish.go, go.mod, go.sum
https://github.com/gravitl/netmaker/pull/2550
refer https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/528
=> NET-528: Skip Endpoint Detection for Static Hosts

functions/daemon.go
=> Revert "don't close wg interface on soft reset"

config/config.go, functions/mqhandlers.go, functions/mqpublish.go, ncutils/netclientutils.go
- Resolves the issue seen with random ports on client
refer https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/608
=> NET-608: Random Port Issue

config/oldconfig.go, config/server.go, functions/mqpublish.go, go.mod, go.sum
=> update go mod

release.md
=> v0.21.0 release notes

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.21.1

functions/mqhandlers.go
=> NET-630: set subscription for node when added from UI

functions/mqhandlers.go
=> clear retained message on host version upgrade

daemon/common_darwin.go, functions/use_version.go, main.go
=> NET-641: Fixed Auto Upgrade for Darwin

nmproxy/nm-proxy.go
=> NET-741: remove proxy dump

release.md
=> v0.21.2 release notes

daemon/common.go, functions/daemon.go
=> fix(NET-711): remove all lockfiles on daemon start

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.22.0

.github/workflows/test.yml
=> remove freebsd from ci test

functions/push.go
=> NET-879: push over api if mq connection fails

config/node.go, functions/server.go
=> NET-876: cleanup server config on leave

release.md
=> release notes fixes v0.22.0

release.md
=> docs: release notes for v0.22.0

gui/main.go, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.22.1

functions/daemon.go
=> add restore default gateway when quit and reset

functions/daemon.go, functions/mqhandlers.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> add error handle for restore default gateway code

scripts/netclient.sh
=> fix: ENDPOINT env variable not working

functions/daemon.go, functions/mqhandlers.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> Internet Gw error handling and resolve conflict

go.mod, go.sum, wireguard/wireguard_linux.go, wireguard/wireguard_unix.go
=> fix(NET-732): userspace wireguard compatibility on linux

functions/mqhandlers.go, wireguard/wireguard_linux.go
=> add error handling for restore InternetGw

functions/mqhandlers.go, go.mod, go.sum, wireguard/wireguard_darwin.go
=> add InternetGw for Hostpull

wireguard/wireguard.go, wireguard/wireguard_windows.go
=> fix issue for InternetGw for Windows

config/config.go, functions/daemon.go, functions/mqhandlers.go, wireguard/wireguard.go, wireguard/wireguard_darwin.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> add InternetGw with higher metric

wireguard/wireguard_windows.go
=> remove debug log

wireguard/wireguard_linux.go
=> add logic to check and reset metric for original gw

config/config.go, functions/daemon.go, functions/mqhandlers.go, wireguard/wireguard_darwin.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> add InternetGw in a separate route table and add rules to activate it

wireguard/wireguard_linux.go
=> add func to get local ip from default interface name

functions/daemon.go, wireguard/wireguard.go, wireguard/wireguard_darwin.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> remove SetNmServerRoutes and RemoveNmServerRoutes

wireguard/wireguard_windows.go
=> add automatic metric calculation for Win

functions/pull.go
=> NET-1008: reset interface on listen port change

wireguard/wireguard_linux.go
=> add rule to bypass route prefix 0 only in main

config/config.go, config/node.go, config/server.go, firewall/firewall.go
=> NET-1041: update global config on defer when no err

release.md
=> docs(NET-990): update release notes for v0.23.0

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.23.1

wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> fix adapter keep creating issue on Win

functions/daemon.go
=> NET-1059: use host id and pass for emqx broker

ncutils/netclientutils.go
=> NET-958: remove netmaker ip ref

daemon/common_windows.go, functions/daemon.go, functions/mqhandlers.go, functions/mqpublish.go, functions/uninstall.go, ncutils/netclientutils_windows.go
=> turn off hole punching when static endpoint is enabled

firewall/firewall_linux.go, functions/localport_linux.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> NET-1088 and NET-1111

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update to v0.24.0

firewall/iptables_linux.go, firewall/nftables_linux.go
=> NET-1133: Dual Stack network egress routing rules bug fix

wireguard/wireguard_windows.go
=> fix Windows egress route issue

wireguard/wireguard_darwin.go
=> NET-1143: Darwin IPv6 interface Static route fix

release.md
=> v0.24.0 release notes

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.24.1

cache/iface_cache.go, functions/daemon.go, functions/mqhandlers.go, wireguard/types.go, wireguard/wireguard_darwin.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> remove egress route when External route is removed

cmd/join.go, cmd/register.go, functions/register_sso.go
- Validation func for SSO join
=> NET-1061: Add args validate func for join via SSO

local/local.go
=> NET-1221:comment the ipforward setup for Win and Mac

wireguard/types.go, wireguard/wireguard_darwin.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
=> NET-1238:do not save cache if egress route set failed

release.md
=> v0.24.1 release notes

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update develop to v0.24.2

daemon/openrc_linux.go
(cherry picked from commit 6f2800f49402cd5fe354fd77340666b424b7bf17)
=> fix log file on k8s issue

wireguard/wireguard_linux.go
=> NET-1218:add metric for egress route on Linux

functions/daemon.go, functions/mqpublish.go
=> NET-1258:fix endpoint address issue after ipv4 is disabled

cmd/install.go
=> NET-1223:deprecate Windows cmd install

daemon/openrc_linux.go
=> NET-1189:fix log file on k8s issue

functions/daemon.go, functions/mqhandlers.go
=> NET-1260:fix gateway change issue

functions/daemon.go, functions/mqpublish.go, stun/stun.go
=> use only stun to discover public ip

functions/daemon.go, functions/fail_over.go, functions/mqpublish.go, metrics/metrics.go, wireguard/wireguard_linux.go
1.  Add mqclient check before publish
2. change some of the log messages from Error to Warn if the message returned does not block the code logic.
=> NET-1278: add mqclient check and change some of the log messages to Warn

functions/daemon.go, networking/server-pong.go
=> NET-1346:enhance the lisening port on both of ipv4 and ipv6

cmd/install.go
=> Revert "NET-1223:deprecate Windows cmd install"

release.md
=> v0.24.2 release notes

functions/daemon.go
=> NET-1315:fix ipv6 only wgPublicListenPort issue

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
updating develop to v0.24.3
NET-1359
=> update develop to v0.24.3

go.mod, go.sum
=> Revert "Bump golang.org/x/net from 0.25.0 to 0.26.0"

functions/fail_over.go
=> check if there is handshake and ignore tcp ping

cmd/register.go
=> NET-1468:set endpoint to static if endpoint is specified

release.md
=> v0.24.3 release notes

main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
update develop to v0.25.0
NET-1438
- [x ] My changes affect only 10 files or less.
- [x ] I have performed a self-review of my code and tested it.
- [x ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [x ] My functions are <= 80 lines.
- [ x] I have had my code reviewed by a peer.
- [ x] My unit tests pass locally.
- [ x] Netclient & Netmaker are awesome.
=> update develop to v0.25.0

cmd/root.go, config/config.go, config/node.go, config/server.go, functions/encryption.go, functions/mqhandlers.go, wireguard/wireguard_linux.go
=> NET-1466:add debug log for descypt message

wireguard/wireguard_linux.go
=> NET-1557:fix inetGW issue

scripts/netclient.sh
=> NET-1556:add sleep in docker start script for endpoint issue

.github/workflows/test.yml, go.mod
=> Updated the go version to 1.23 and workflows use go.mod version

wireguard/wireguard_linux.go
=> NET-1616:add fix for checking gateway issue

wireguard/wireguard_linux.go
* add fix for checking gateway issue
* fix ipv6 defaultgw issue
=> NET-1616:add fix for checking gateway issue (#881)

go.mod, go.sum
=> downgrade the eclipse/paho to v1.4.3

.github/workflows/build_upload_bin.yml
=> Build and deploy netclient bins

functions/daemon.go, functions/dns.go, functions/uninstall.go
=> NET-1594:remove calls to old hosts file logic

metrics/metrics.go
=> NET-1531: fix metric uptime issue

dns/config_linux.go
=> NET-1733:add default upsteam DNS servers if it's not found

.github/workflows/build_upload_bin.yml
=> updated build_upload_bin.yml fix the missing quote

release.md
=> v0.26.0 release notes

functions/mqpublish.go
=> NET-1778:fix UpdateHost call issue

firewall/iptables_linux.go, firewall/nftables_linux.go, functions/daemon.go
=> NET-1801: Add src address and ipv6 support for nftables egress networks

firewall/acl.go, firewall/iptables_linux.go, go.mod, go.sum
=> configure adv rules for user policies

.github/workflows/build_upload_bin.yml, .goreleaser.yaml
added
- windows_amd64
- darwin_amd64
- darwin_arm64
to the .goreleaser.yaml
=> Added the missing architectures in the gorelease config

cmd/root.go, config/node.go, functions/daemon.go, functions/localport.go, functions/mqpublish.go, functions/register.go, functions/register_sso.go, metrics/metrics.go, ncutils/netclientutils.go, networking/server-pong.go, networking/utils.go
=> NET-1780: Run Metrics And Iface Detection only on necessary IPs

.github/workflows/patch.yml
=> fixed the github patch workflow

metrics/metrics.go
=> fix ipv6 ping issue

.github/workflows/patch.yml
=> fixed the workflow to include CGO_ENABLED=0

README.md, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> update release version

Dockerfile
=> change dockerfile for Alpine upgrade

firewall/acl.go, firewall/firewall.go, firewall/ingress.go, firewall/iptables_linux.go, firewall/nftables_linux.go, metrics/metrics.go
=> add lint ignore on ping pkg

functions/daemon.go, functions/mqhandlers.go, metrics/metrics.go
=> NET-1858:fix manage_dns on/off issue and remove debug log

release.md
=> v0.30.0 release notes

.github/workflows/patch.yml
=> Update patch.yml indentation fix

dns/config.go
=> NET-1916: Check if server cfg is nil

firewall/nftables_linux.go, ncutils/netclientutils.go
=> Release v0.30.0

functions/mqhandlers.go
=> NET-1920: Collect Metrics on peer update

firewall/acl.go, firewall/egress.go, firewall/firewall.go, firewall/ingress.go
=> NET-1902: add mutex to firewall ops

config/config.go, functions/mqpublish.go
=> NET-1942: add safety for ip checks

functions/mqpublish.go
=> fix ip detection

functions/mqpublish.go
=> NET-1945: switch to using stun for ip check

cmd/pull.go, functions/daemon.go, functions/fail_over.go, functions/mqhandlers.go, functions/mqpublish.go, functions/pull.go, go.mod, go.sum, metrics/metrics.go, ncutils/netclientutils.go, wireguard/wireguard.go
=> NET-1941: Optimise metrics collection

dns/config_linux.go
=> fix(go): bug in dns linux config;

functions/mqhandlers.go, networking/utils.go
=> NET-1947: check if peer endpoint interface exists on host before detecting

config/server.go, dns/resolver.go, functions/mqhandlers.go, go.mod, go.sum
=> NET-1978: add additional nameservers

scripts/netclient.sh
Add IS_STATIC_PORT env var to netclient.sh to support setting netclient in docker container to use static port.
=> feat(go): add is static port env var

firewall/iptables_linux.go, firewall/nftables_linux.go
=> NET-1911: optimise ACl rules

functions/daemon.go, functions/egress.go, functions/mqhandlers.go, go.mod, go.sum
=> NEt-1990: handle egress HA failover

README.md, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> v0.90.0 release notes

functions/mqhandlers.go, functions/mqpublish.go
=> NET-1950: Auto Sync Server settings

dns/config_windows.go
=> NET-2051: add search domains on windows;

README.md, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> v0.99.0: update release notes, bump up version

wireguard/wireguard_darwin.go
=> V0.99 fixes v1

firewall/iptables_linux.go, firewall/nftables_linux.go, wireguard/types.go
=> fix iptable rules for single node egress

README.md, main.go, release.md, resources/windows/netclient.exe.manifest.xml, versioninfo.json
=> v1.0.0 release notes

README.md
Fixed broken links in readme file
go to https://github.com/gravitl/netclient and click the links under Installation and Usage
=> Fix for Broken Links in README.md

functions/daemon.go, functions/mqhandlers.go, wireguard/egress.go, wireguard/wireguard.go
=> NM-22: optimise egress HA peer updates

Dockerfile, cmd/join.go, cmd/register.go, firewall/firewall_linux.go, scripts/netclient.sh
=> NM-11: add firewall args to join cmd

functions/mqhandlers.go, functions/pull.go
=> Release v1.1.0
