gravitl/netclient

cmd/use.go, functions/use_version.go
All released binaries must adhere to the following name format `netclient-{platform}-{architecture}`
=> Feature: use specific version of netclient

wireguard/types.go, wireguard/wireguard_darwin.go
-> `IP.To16()` is not a valid check for ipv4 addrs instead only check if ipv4 by `IP.To4()` else apply as ipv6
=> darwin apply addrs fix

cmd/leave.go, functions/daemon.go, functions/mqhandlers.go, functions/uninstall.go
To test: 
- Add a node to a server
- Delete said node from server
- node should be removed locally from netclient configs and from server DB
Relevant netclient logs: `<node ID>, "was removed from network", <network ID>`
=> refactored how daemon treats node delete message

functions/mqhandlers.go, functions/mqpublish.go, nmproxy/config/config.go
- > func to clear retained message in the topic
Testing steps:
=> Gra 1005/clear mq topic

functions/mqhandlers.go, functions/mqpublish.go, nmproxy/nm-proxy.go
-> only update public listen port during checkin
**Server version : https://github.com/gravitl/netmaker/pull/1978**
testing steps:
=> Gra 1060/publish listen port bug

functions/list.go
=> put nil check on peers

nmproxy/router/iptables_linux.go
-> added netmaker tags to jump rules, better way to handle the cleanup of rules
testing steps:
=> Gra 1054/route manager

functions/list.go
=> added host nil check during peers get

functions/mqhandlers.go
- this will fix clearing out the interface on leaving the last network
Testing Steps:
=> GRA-1154: skip peer update if no nodes exist

nmproxy/manager/manager.go, nmproxy/proxy/proxy_helper.go, nmproxy/server/server.go
server version: https://github.com/gravitl/netmaker/pull/2023
Testing:
=> GRA-1156: reset ext.client proxy connection on endpoint change

functions/join.go
"log" is unused in join.go and can't build. removed it.
=> deleted unused import "log"

functions/mqhandlers.go, functions/mqpublish.go, nmproxy/config/config.go
Testing:
**check-in happens every 1-minute on client**
=> GRA-1187: enable proxy automatically  for machines behind NAT only once during lifetime of daemon

functions/daemon.go, functions/mqhandlers.go, functions/pull.go
Cleaned up some pointless/unused function calls as well
Reference server on PR https://github.com/gravitl/netmaker/tree/GRA-1180-default-host-delete
To test:
=> Gra 1180 default host node removal

wireguard/wireguard_linux.go
It seems someone copied the log message statement from a few lines earlier and forgot to adjust the message from addr to route.
=> fix copy&paste error in log message

functions/daemon.go
Critical issue:
When mqtt singletons are created, they are referencing broker incorrectly since 0.18.2 update
fixed it.
To test:
=> GRA-1360 - fixed mqtt singleton

README.md
a small typo fix in the readme for netclient
=> fix typo in the readme commands section for netclient

functions/list.go, nmproxy/manager/manager.go, nmproxy/peer/peer.go, nmproxy/server/server.go
nil checks are added for peer endpoint to avoid nil pointer errors
=> GRA-1436: nil checks for peer (ext. client) endpoint

.github/workflows/branchtest.yml
changing the network name to netmaker since terraform no longer makes a terraform network in branchtest.yml
=> change network name to netmaker from terraform

networking/server-pong.go
Fixed issue with client-pong improperly converting byte data to runes. Incorrect encoding led to always returning a "!=" when receiving a client-ping, meaning a host can ping itself, receive a success response, and set a local interface as the interface.
1. Create a dummy interface with the same ip address on two clients with the current release **before registering with the server:**
```
ip link add dummy1 type dummy
ip addr add 10.11.12.13/24 dev dummy1
ip link set dummy1 up
```
2. Register the clients with the server
3. Both clients should set the other clients' endpoint to 10.11.12.13 after ~5 minutes (look at wg)
4. unregister the clients and stop the daemon if still running. Delete the wireguard interface if it exists
5. install the new netclient from this branch
6. re-register the …
=> fixed data endcoding

functions/daemon.go, functions/register.go, nmproxy/stun/stun.go
Details [here](https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/347)
=> fix(NET-347): deduce public endpoint on daemon start

functions/mqhandlers.go
I reduced log level of a msg from Error to Warn because it was appearing too frequently and it was not actually indicating a  problematic situation.
Run netclient joining a network
Observe "failed to check for endpoint on peer" is not printed frequently.
=> [NET-381] Reduce log level of a msg from Error to Warn

functions/daemon.go, functions/mqhandlers.go, functions/mqpublish.go, go.mod, go.sum, nmproxy/turn/turn_helper.go
- Remove Endpoint detection from host model
- Reset turn connection check timer on peer update
- Remove auto switch on of proxy
- No testing is required
=> Scaling fixes

functions/daemon.go
check for errors when daemon creates or configures wireguard interface
=> error checks

functions/mqhandlers.go, go.mod, go.sum, wireguard/types.go, wireguard/wireguard_darwin.go, wireguard/wireguard_freebsd.go, wireguard/wireguard_linux.go, wireguard/wireguard_windows.go
- On darwin,freebsd Set Routes via Gw to work on multiple networks correctly
- set additional routes via different func
- set egress routes on peer update
https://github.com/gravitl/netmaker/pull/2452
=> NET-431: Fix for multi-network Interface routes on darwin,freebsd and Egress routes fix

go.mod, go.sum, metrics/metrics.go
-> removed the fmt logs from TCP ping pkg  after forking it - https://github.com/gravitl/tcping/pull/1
=> NET-525: import forked tcp ping pkg

config/config.go, config/node.go, config/server.go
gui.yml remains world readable as it needs to be read by any user running netclient-gui
=> make config files readable by root only

wireguard/types.go, wireguard/wireguard.go
set NCIface.Config.Peers to nil  when no peers.
prevents ioctl: bad address error on freebsd in wgctrl.(*Client).ConfigureDevice()
=> Net 607 - set peers to nil when no peers

config/node.go, config/oldconfig.go, wireguard/iface.go
Remove references to Node.PersistentKeepalive, moved to host level.
https://github.com/gravitl/netclient/compare/net-562-adapt?expand=1#diff-e14bc0ffe852c3142c0d54fd6df7a61dc8c7b6da0c341a02b445a10ad856d536L36
https://github.com/gravitl/netclient/compare/net-562-adapt?expand=1#diff-70584e473f85ce4411dcfc16e85af66d4b0692f504a11c7e38e3e763c665f658L192
https://github.com/gravitl/netclient/compare/net-562-adapt?expand=1#diff-70584e473f85ce4411dcfc16e85af66d4b0692f504a11c7e38e3e763c665f658L147
NET-562
https://github.com/gravitl/netmaker/pull/2604
=> Remove refs to Node.PKA

Dockerfile
Add wireguard-tools to runner docker image layer so that cleanup function in netclient.sh can do `wg show interfaces`
Don't encounter failure logs about wg not being installed when closing netclient docker
=> [NET-624] Add wireguard-tools dockerfile

functions/daemon.go, functions/mqhandlers.go, functions/register.go, ncutils/netclientutils.go, nmproxy/stun/stun.go, nmproxy/turn/turn_helper.go, nmproxy/wg/wg.go, wireguard/types.go, wireguard/wireguard.go
=> NET-748: Handle Peer with nil IP, fallback to ip service if stun fails

functions/register_sso.go
this is part of a security fix to prevent non-admin users from registering
Pair with: https://github.com/gravitl/netmaker/pull/2778
=> fix(NET-887): show reason for auth failure

functions/daemon.go
=> NET-1106:do not set .EndpointIP if it is an IPv6 only host

functions/mqhandlers.go, functions/uninstall.go, wireguard/wireguard_darwin.go, wireguard/wireguard_windows.go
=> NET-1148:add lock for multinet on Win

scripts/netclient.sh
When running netcilent in a docker container, it's impossible to change the log verbosity during startup without modifying the docker entrypoint
=> Add env var to set verbosity when running in docker container

functions/mqhandlers.go
=> NET-1269:add mutex for upgrade

stun/stun.go
=> NET-1341:fix ipv6 stun dns resolve issue

functions/mqpublish.go
=> NET-1315:exclude InetClient for network change detection

.github/workflows/patch.yml
=> New workflow to patch netclient and update the fileserver and github releases

stun/stun.go
=> fix stun server switch issue

functions/daemon.go, functions/mqpublish.go, stun/stun.go
=> Stun TimeOut fixes, Use Ip servers to check ip changes
